# Generated by Django 3.2.8 on 2022-05-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('email_from', models.EmailField(max_length=254)),
                ('comentario', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
