# Generated by Django 3.2.8 on 2022-05-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn_SignUp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_been_tested',
        ),
        migrations.AddField(
            model_name='user',
            name='has_been_tested_abc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_been_tested_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_been_tested_simple_phrases',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_been_tested_simple_words',
            field=models.BooleanField(default=False),
        ),
    ]
