# Generated by Django 3.2.8 on 2022-05-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn_SignUp', '0002_auto_20220511_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_been_tested_abc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_been_tested_color',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_been_tested_simple_phrases',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_been_tested_simple_words',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_video_abc',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_video_simple_phrases',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_video_simple_words',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
