# Generated by Django 3.2.8 on 2022-05-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn_SignUp', '0005_auto_20220512_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_video_abc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_video_color',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_video_simple_phrases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_video_simple_words',
            field=models.IntegerField(default=0),
        ),
    ]
